import 'package:flutter/material.dart';

/// Flutter icons Message2
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Message2
///      fonts:
///       - asset: fonts/Message2.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///


class Message2 {
  Message2._();

  static const _kFontFam = 'Message2';
  static const String? _kFontPkg = null;

  static const IconData message2 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
